name       : adapta-gtk-theme
version    : 3.92.2.43
release    : 126
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.92.2.43.tar.gz : 666442eb4c3cca3e206f53eb9df1da7c14fc72b82d8f3ae4dd75ad9e0c7c3433
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/parallel.patch
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-parallel
build      : |
    make -j1
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    make install -j1 DESTDIR=$installdir
