name       : adapta-gtk-theme
version    : 3.90.0.89
release    : 38
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.90.0.89.tar.gz : ae53f37a794d21a18a26bc40a382759b3cd310bc68db4de8074e78cc229625e3
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
    - parallel
    - sassc
setup      : |
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-xfce
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
