name       : adapta-gtk-theme 
version    : 3.20.2.87
release    : 1
source     :
    - https://github.com/tista500/Adapta/archive/3.20.2.87.tar.gz : 3b52b392c6a5130d4443ecb21ceff3b93a5f2b0f3af6ca74944441069b2646e5
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    rm -rf $themeLocation/{cinnamon,gtk-3.20,README.md,unity}
    mv $themeLocation/gtk-3.18 $themeLocation/gtk-3.0
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
