name       : adapta-gtk-theme 
version    : 3.20.3
release    : 2
source     :
    - https://github.com/tista500/Adapta/archive/3.20.3.23.tar.gz : c407c76b78e15a9d7134d31d1ef344c5d86576ec6a325df92bbcda05c0b1928b
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
