name       : adapta-gtk-theme
version    : 3.89.3.84
release    : 26
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.89.3.84.tar.gz : ac1fa3c49a9c391da4839576ac77fc82ba624f9910eb89109c544b0f87b944f7
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(librsvg-2.0)
    - bundler
    - inkscape
    - parallel
    - ruby-sass
    - sassc
setup      : |
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-xfce
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
