name       : adapta-gtk-theme
version    : 3.89.3.99
release    : 28
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.89.3.99.tar.gz : 751bc43f6fe8230abe5d07f65da5f7126510e74a90ba17b4fcf0c0b78a121467
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
    - parallel
    - sassc
setup      : |
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-xfce
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
