name       : adapta-gtk-theme 
version    : 3.21.1.100
release    : 7
source     :
    - https://github.com/tista500/Adapta/archive/3.21.1.100.tar.gz : fef7608124b2b79fde6f5d99a8e2c9ecaec1bee479181c1be2179ac01cf84943
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
