name       : adapta-gtk-theme
version    : 3.91.0.140
release    : 57
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.91.0.140.tar.gz : f283edca2f98c816b77dfefcffa4f9c16cf8f8e0468b902c7f8e652f39e7603b
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/parallel.patch
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-parallel
build      : |
    make -j1
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    make install -j1 DESTDIR=$installdir
