name       : adapta-gtk-theme
version    : 3.92.1.94
release    : 117
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.92.1.94.tar.gz : fc52a8ff8e3312cda1bb7cf0644a4d45f489e180062cca6d472f56034b0ed838
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/parallel.patch
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-parallel
build      : |
    make -j1
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    make install -j1 DESTDIR=$installdir
