name       : adapta-gtk-theme
version    : 3.89.5.40
release    : 30
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.89.5.40.tar.gz : da368a4bbe4e3f19658406b1359a90cdd51cc7519f7ba4d5d300b1a9b1955182
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
    - parallel
    - sassc
setup      : |
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-xfce
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
