name       : adapta-gtk-theme
version    : 3.91.2.86
release    : 94
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.91.2.86.tar.gz : 681aa77f0d974c4968de46f2707015f56cc14f6de524adfb35e8e596ace982d4
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/parallel.patch
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-parallel
build      : |
    make -j1
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    make install -j1 DESTDIR=$installdir
