name       : adapta-gtk-theme 
version    : 3.18.9
release    : 13
source     :
    - https://github.com/tista500/Adapta/archive/3.18.9.55.tar.gz : ce84914474af8f6276f120717b068a2629c0bf4fedd8f27ed6c03d562d4a7393
license    : GPL-2.0
summary    : Adapta theme
description: |
        An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
     ./autogen.sh $CONFOPTS \
         --disable-cinnamon \
         --enable-gnome-shell \
         --disable-metacity \
         --disable-unity \
         --disable-xfwm \
         --with-gnome=3.18
build      : |
    %make
install    : |
    %make_install
