name       : adapta-gtk-theme
version    : 3.21.5.91
release    : 14
source     :
    - https://github.com/tista500/Adapta/archive/3.21.5.91.tar.gz : 79ed8b44c00016bc5b9b8b5e6c4251556ebaec43f35f998d9dc6379a7ff66605
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - bundler
    - inkscape
    - parallel
    - ruby-sass
setup      : |
    %autogen --enable-chrome --enable-plank
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
