name       : adapta-gtk-theme 
version    : 3.20.3.56
release    : 4
source     :
    - https://github.com/tista500/Adapta/archive/3.20.3.56.tar.gz : 890f0758b6c00b26fa40840c41e8e0d2155575cad4d112eecfd1bc5bbde30e26
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
