name       : adapta-gtk-theme 
version    : 3.21.1.215
release    : 9
source     :
    - https://github.com/tista500/Adapta/archive/3.21.1.215.tar.gz : 09224ddb8760744657943d5ddeb15ad274485427674673231f2ff80ae707de43
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    themeLocation=$installdir/usr/share/themes/Adapta
    %make_install
    chmod 0755 $themeLocation
    chmod -R 0644 $themeLocation/*
