name       : adapta-gtk-theme
version    : 3.94.0.149
release    : 179
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.94.0.149.tar.gz : db69ef4e2de34d125b8a05fcd8881fc6d54fa7c4c194cadf69200760ed940cac
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
rundeps    :
    - noto-sans-ttf
setup      : |
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
