name       : adapta-gtk-theme
version    : 3.94.0.129
release    : 174
source     :
    - https://github.com/adapta-project/adapta-gtk-theme/archive/3.94.0.129.tar.gz : 408ff280bbc6c72f062de7f10fe8ba9025ca6149c754ac3aa8387415ee3b69b5
license    : GPL-2.0
component  : desktop.theme
summary    : Adapta theme
description: |
    An adaptive Gtk+ theme based on Material Design Guidelines. Lots of elements are forked from Flat-Plat theme.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - gnome-shell
    - inkscape
    - sassc
rundeps    :
    - noto-sans-ttf
setup      : |
    %patch -p1 < $pkgfiles/parallel.patch
    %autogen \
        --enable-chrome \
        --enable-plank \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-gtk_next \
        --disable-openbox \
        --disable-unity \
        --disable-parallel
build      : |
    %make
install    : |
    %make_install
